# -*- coding: utf-8 -*-
"""시연용 BAT 2종을 CP949+CRLF로 생성하는 빌더.

bat-file-craft 스킬 패턴(#11) — 한글 출력 BAT은 CP949+CRLF로 저장해야
CMD 파서/콘솔에서 깨지지 않는다. echo 내부 괄호/리다이렉트 문자는 제거(ASCII만).
zip 생성/해제는 Windows 내장 bsdtar(%WINDIR%\\System32\\tar.exe)를 '명시 경로'로 호출.
(PATH에 Git의 GNU tar가 먼저 잡히면 zip 생성이 깨질 수 있어 절대경로 사용. 2GB 초과 안전.)

생성물:
  scripts/demo/1_시연번들_내보내기.bat   (소스 PC: gitignore된 DB/.env/모델을 demo_bundle.zip 한 파일로)
  scripts/demo/2_시연_설치_및_실행.bat    (시연 PC: zip 해제 + 배치 + venv/pip/npm + 서버 기동)
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def save(name, lines):
    content = "\r\n".join(lines) + "\r\n"
    data = content.encode("cp949")
    bare = data.count(b"\n") - data.count(b"\r\n")
    assert bare == 0, f"{name}: bare LF {bare}"
    assert b"^(call" not in data, f"{name}: ^(call 위험 패턴"
    with open(os.path.join(HERE, name), "wb") as f:
        f.write(data)
    print(f"[OK] {name}  ({len(lines)} lines, {len(data)} bytes, CRLF/CP949)")


# ============================================================
# 1) 내보내기 BAT (소스 PC) -> demo_bundle.zip
# ============================================================
export_lines = [
    "@echo off",
    "setlocal enabledelayedexpansion",
    "chcp 949 >nul",
    "title AI 코치 - 시연 번들 내보내기",
    "",
    "rem 이 bat은 scripts\\demo\\ 안에 있음. 상위 2단계가 프로젝트 루트.",
    'pushd "%~dp0..\\.."',
    'set "ROOT=%CD%"',
    "popd",
    'set "BUNDLE=%ROOT%\\demo_bundle"',
    'set "ZIP=%ROOT%\\demo_bundle.zip"',
    'set "TAR=%WINDIR%\\System32\\tar.exe"',
    "",
    "echo ============================================================",
    "echo  AI 코치 - 시연 번들 내보내기",
    "echo  소스 PC에서 실행. demo_bundle.zip 한 파일을 USB로 옮기세요.",
    "echo ============================================================",
    "echo.",
    "echo  프로젝트 루트: %ROOT%",
    "echo.",
    "",
    'if exist "%TAR%" goto :tarok',
    "echo   [오류] Windows tar 를 찾을 수 없습니다: %TAR%",
    "echo          Windows 10 1809 이상이 필요합니다.",
    "pause",
    "exit /b 1",
    ":tarok",
    "",
    "rem === staging 폴더 정리 ===",
    'if exist "%BUNDLE%" rmdir /s /q "%BUNDLE%"',
    'mkdir "%BUNDLE%"',
    "",
    "rem === 1. ChromaDB 복사 - 필수 ===",
    "echo [1/4] ChromaDB 수집...",
    'if not exist "%ROOT%\\data\\chroma_db\\chroma.sqlite3" echo   [경고] ChromaDB가 비어있음. 인제스트 먼저 하세요.',
    'robocopy "%ROOT%\\data\\chroma_db" "%BUNDLE%\\data\\chroma_db" /E /NFL /NDL /NJH /NJS /NC /NS /NP >nul',
    "echo   [완료] data\\chroma_db",
    "echo.",
    "",
    "rem === 2. .env 복사 - API 키 포함, 취급 주의 ===",
    "echo [2/4] .env 수집...",
    'if exist "%ROOT%\\.env" copy /y "%ROOT%\\.env" "%BUNDLE%\\.env" >nul',
    'if exist "%BUNDLE%\\.env" echo   [완료] .env  - 주의: API 키 포함, 외부 유출 금지',
    'if not exist "%ROOT%\\.env" echo   [건너뜀] .env 없음',
    "echo.",
    "",
    "rem === 3. meta.db - 재인제스트용, 선택 ===",
    "echo [3/4] meta.db 수집...",
    'if exist "%ROOT%\\data\\meta.db" copy /y "%ROOT%\\data\\meta.db" "%BUNDLE%\\data\\meta.db" >nul',
    'if exist "%BUNDLE%\\data\\meta.db" echo   [완료] data\\meta.db',
    'if not exist "%ROOT%\\data\\meta.db" echo   [건너뜀] meta.db 없음',
    "echo.",
    "",
    "rem === 4. bge-m3 모델 캐시 - 폐쇄망/인터넷 없는 PC용, 약 2.2GB ===",
    "echo [4/4] bge-m3 모델 캐시 포함 여부",
    "echo   시연 PC에 인터넷이 없으면 Y  [약 2.2GB, 시간 걸림]",
    "echo   인터넷이 되면 N  [첫 실행 시 자동 다운로드]",
    'set "INCMODEL=N"',
    'set /p "INCMODEL=  포함할까요? Y/N [기본 N]: "',
    'if /i not "!INCMODEL!"=="Y" goto :skipmodel',
    'set "HFHUB=%USERPROFILE%\\.cache\\huggingface\\hub\\models--BAAI--bge-m3"',
    'if not exist "!HFHUB!" goto :nomodel',
    "echo   [수집] bge-m3 모델 캐시... 잠시만 기다리세요",
    'robocopy "!HFHUB!" "%BUNDLE%\\hf_cache\\hub\\models--BAAI--bge-m3" /E /NFL /NDL /NJH /NJS /NC /NS /NP >nul',
    "echo   [완료] hf_cache\\hub\\models--BAAI--bge-m3",
    "goto :skipmodel",
    ":nomodel",
    "echo   [경고] 모델 캐시 없음: !HFHUB!",
    ":skipmodel",
    "echo.",
    "",
    "rem === 안내문 생성 ===",
    'set "RM=%BUNDLE%\\READ_ME_먼저.txt"',
    '>"%RM%" echo [AI 코치 시연 번들]',
    '>>"%RM%" echo.',
    '>>"%RM%" echo 1. 시연 PC에서 git pull 로 소스를 최신화',
    '>>"%RM%" echo 2. demo_bundle.zip 을 프로젝트 루트에 복사',
    '>>"%RM%" echo 3. scripts\\demo\\2_시연_설치_및_실행.bat 더블클릭',
    '>>"%RM%" echo 4. 브라우저가 열리면 시연 시작',
    "",
    "rem === zip 압축 + staging 삭제 ===",
    "echo [압축] demo_bundle.zip 생성 중... 모델 포함 시 수 분 소요",
    'if exist "%ZIP%" del /q "%ZIP%"',
    '"%TAR%" -a -c -f "%ZIP%" -C "%BUNDLE%" .',
    'if not exist "%ZIP%" (',
    "    echo   [오류] zip 생성 실패",
    "    pause",
    "    exit /b 1",
    ")",
    'rmdir /s /q "%BUNDLE%"',
    "echo.",
    "echo ============================================================",
    "echo  완료! 아래 zip 한 파일을 USB 등으로 시연 PC에 옮기세요:",
    "echo    %ZIP%",
    "echo ============================================================",
    "echo.",
    "pause",
    "endlocal",
]


# ============================================================
# 2) 설치+실행 BAT (시연 PC) <- demo_bundle.zip
# ============================================================
setup_lines = [
    "@echo off",
    "setlocal enabledelayedexpansion",
    "chcp 949 >nul",
    "title AI 코치 - 시연 설치 및 실행",
    "",
    'pushd "%~dp0..\\.."',
    'set "ROOT=%CD%"',
    "popd",
    'set "ZIP=%ROOT%\\demo_bundle.zip"',
    'set "TMP=%ROOT%\\_bundle_tmp"',
    'set "PY=%ROOT%\\.venv\\Scripts\\python.exe"',
    'set "TAR=%WINDIR%\\System32\\tar.exe"',
    "",
    "echo ============================================================",
    "echo  AI 코치 - 시연 설치 및 실행  [시연 PC에서 실행]",
    "echo ============================================================",
    "echo  프로젝트 루트: %ROOT%",
    "echo.",
    "",
    "rem === 0. demo_bundle.zip 압축 해제 + 파일 배치 ===",
    "echo [0/5] 전달받은 zip 압축 해제 및 배치",
    'set "SRC="',
    'if exist "%ZIP%" goto :unzip',
    'if exist "%ROOT%\\demo_bundle\\data\\chroma_db\\chroma.sqlite3" goto :usefolder',
    "echo   [경고] demo_bundle.zip 도 demo_bundle 폴더도 없음. DB 없이 진행하면 검색이 빈 결과.",
    "goto :placedone",
    ":usefolder",
    'set "SRC=%ROOT%\\demo_bundle"',
    "goto :place",
    ":unzip",
    'rmdir /s /q "%TMP%" 2>nul',
    'mkdir "%TMP%"',
    '"%TAR%" -x -f "%ZIP%" -C "%TMP%"',
    'set "SRC=%TMP%"',
    "echo   [완료] 압축 해제",
    ":place",
    'if exist "!SRC!\\data\\chroma_db\\chroma.sqlite3" robocopy "!SRC!\\data\\chroma_db" "%ROOT%\\data\\chroma_db" /E /NFL /NDL /NJH /NJS /NC /NS /NP >nul',
    'if exist "%ROOT%\\data\\chroma_db\\chroma.sqlite3" echo   [완료] ChromaDB 배치',
    'if exist "!SRC!\\.env" copy /y "!SRC!\\.env" "%ROOT%\\.env" >nul',
    'if exist "!SRC!\\data\\meta.db" copy /y "!SRC!\\data\\meta.db" "%ROOT%\\data\\meta.db" >nul',
    'if exist "!SRC!\\hf_cache\\hub" robocopy "!SRC!\\hf_cache\\hub" "%USERPROFILE%\\.cache\\huggingface\\hub" /E /NFL /NDL /NJH /NJS /NC /NS /NP >nul',
    'if exist "!SRC!\\hf_cache\\hub" echo   [완료] bge-m3 모델 캐시 배치',
    ":placedone",
    "echo.",
    "",
    "rem === .env 점검 ===",
    'if exist "%ROOT%\\.env" goto :envok',
    "echo   [중요] .env 가 없습니다. 루트에 .env 파일을 만들고 아래 2줄을 넣으세요:",
    "echo         GOOGLE_API_KEY=여기에_본인_키",
    "echo         EMBEDDING_PROVIDER=local",
    "echo.",
    ":envok",
    "",
    "rem === 1. Python 확인 ===",
    "echo [1/5] Python 확인",
    "where python >nul 2>nul",
    "if errorlevel 1 (",
    "    echo   [오류] Python 미설치. python.org 에서 3.12 설치 후 다시 실행.",
    "    pause",
    "    exit /b 1",
    ")",
    "echo   [OK] Python 있음",
    "echo.",
    "",
    "rem === 2. 가상환경 + 패키지 ===",
    "echo [2/5] 가상환경/패키지  - 처음만 수 분 소요",
    'if not exist "%PY%" python -m venv "%ROOT%\\.venv"',
    'if exist "%PY%" echo   [OK] .venv 준비됨',
    '"%PY%" -m pip install --upgrade pip >nul',
    "echo   [설치] torch CPU 버전",
    '"%PY%" -m pip install torch --index-url https://download.pytorch.org/whl/cpu',
    "echo   [설치] requirements.txt",
    '"%PY%" -m pip install -r "%ROOT%\\requirements.txt"',
    "echo.",
    "",
    "rem === 3. Node / 프론트엔드 ===",
    "echo [3/5] 프론트엔드 패키지",
    "where npm >nul 2>nul",
    "if errorlevel 1 (",
    "    echo   [오류] Node.js npm 미설치. nodejs.org 에서 LTS 설치 후 다시 실행.",
    "    pause",
    "    exit /b 1",
    ")",
    'if not exist "%ROOT%\\frontend\\node_modules" goto :npminstall',
    "echo   [건너뜀] node_modules 이미 있음",
    "goto :npmdone",
    ":npminstall",
    'pushd "%ROOT%\\frontend"',
    "call npm install",
    "popd",
    "echo   [완료] node_modules 설치",
    ":npmdone",
    "echo.",
    "",
    "rem === 정리 ===",
    'if exist "%TMP%" rmdir /s /q "%TMP%" 2>nul',
    "",
    "rem === 4. 서버 기동 - 새 창 2개 ===",
    "echo [4/5] 백엔드/프론트엔드 기동",
    'start "AI코치 백엔드" cmd /k "cd /d %ROOT% && set EMBEDDING_PROVIDER=local && %PY% -m uvicorn backend.main:app --host 127.0.0.1 --port 8000"',
    'start "AI코치 프론트" cmd /k "cd /d %ROOT%\\frontend && npm run dev"',
    "echo.",
    "",
    "rem === 5. 브라우저 ===",
    "echo [5/5] 서버 기동 대기 후 브라우저 열기",
    "timeout /t 8 /nobreak >nul",
    'start "" http://localhost:3000/',
    "echo.",
    "echo ============================================================",
    "echo  완료! 브라우저에서 http://localhost:3000 확인",
    "echo  첫 질문은 bge-m3 로딩으로 수십 초 걸릴 수 있습니다.",
    "echo ============================================================",
    "echo.",
    "pause",
    "endlocal",
]


save("1_시연번들_내보내기.bat", export_lines)
save("2_시연_설치_및_실행.bat", setup_lines)
print("done")
